services:
  # - type: web
  #   plan: free
  #   name: comp4537-lab0
  #   runtime: node
  #   repo: https://github.com/orangeepop/COMP4537.git
  #   buildCommand: npm install
  #   startCommand: node lab/0/server0.js

  # - type: web
  #   plan: free
  #   name: comp4537-lab1
  #   runtime: node
  #   repo: https://github.com/orangeepop/COMP4537.git
  #   buildCommand: npm install
  #   startCommand: node lab/1/server1.js

  - type: web
    plan: free
    name: comp4537-lab3
    runtime: node
    repo: https://github.com/orangeepop/COMP4537.git
    buildCommand: npm install
    startCommand: node labs/3/getDate/server.js
